apiVersion: v1
kind: Service
metadata:
  name: appservice
  labels:
    app: student
  namespace: mysqldb
spec:
 
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    
    nodePort: 30000
  selector:
    app: employees
    
