apiVersion: v1
kind: Service
metadata:
  name: mysqlservice
  labels:
    app: db
  namespace: mysqldb
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  ports:
  - port: 3306
    targetPort: 3306
    # Optional field
  selector:
    app: db
    
