apiVersion: v1
kind: Pod
metadata:
  labels: 
    app: db
  name: mysql
spec:
  containers:
  - name: mysqldb
    image: 561283682508.dkr.ecr.us-east-1.amazonaws.com/app_repo:v0.1
    ports: 
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value : P@ssw0rd
